Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.box = "generic/ubuntu2004"

    config.vm.provider "vmware_desktop" do |v|
        v.linked_clone = false
        v.gui = false
      end
end