Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.box = "ubuntu/focal"
    config.vm.hostname = "ubuntu-focal64-20.04"

    # 禁用ssh端口转发，使用vmnet8子网的ip也可以访问
    config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disabled: "true"

    config.vm.provider "vmware_desktop" do |v|
        v.nat_device = "vmnet8"
        v.gui = false
        v.vmx["memsize"] = "1024"
        v.vmx["numvcpus"] = "2"
    end

end